name: Compilar y Subir InsertData.exe

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Clonar el código local
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar librerías y PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Compilar a .exe
      run: |
        # Usamos --windowed para ocultar la consola
        # El archivo de salida se llamará "TomarCaptura.exe"
        pyinstaller --noconfirm --onefile --windowed --name "InsertData" InsertData.py

    - name: Subir archivo a Ejecutables
      env:
        GH_TOKEN: ${{ secrets.TOKEN_EJECUTABLES }}
      shell: bash
      run: |
        # 1. Eliminamos el ejecutable anterior si existe. 
        # El "|| true" evita que la acción falle si es la primera vez y el archivo no existe aún.
        gh release delete-asset Produccion "InsertData.exe" --repo idwin1/Ejecutables -y || true
        
        # 2. Subimos el ejecutable recién compilado
        gh release upload Produccion dist/InsertData.exe --repo idwin1/Ejecutables --clobber
